import { test, expect } from "@playwright/test"

function isExternalHref(href) {
  return (
    href.startsWith("http://") ||
    href.startsWith("https://") ||
    href.startsWith("mailto:") ||
    href.startsWith("tel:")
  )
}

function isHashRouteHref(href) {
  return href.startsWith("#/")
}

function isHashSectionHref(href) {
  return href.startsWith("#") && !href.startsWith("#/")
}

function extractSectionId(href) {
  return href.replace(/^#/, "").replace(/^\//, "")
}

test.describe("site smoke and UI validation", () => {
  test("homepage loads and core layout is visible", async ({ page }) => {
    const consoleErrors = []

    page.on("console", (msg) => {
      if (msg.type() === "error") {
        consoleErrors.push(msg.text())
      }
    })

    await page.goto("/#/")
    await expect(page.locator("body")).toBeVisible()
    await expect(page.locator("header")).toBeVisible()
    await expect(page.locator("main")).toBeVisible()
    await expect(page.locator("footer")).toBeVisible()

    expect(
      consoleErrors.filter((err) => !err.toLowerCase().includes("favicon")).length
    ).toBe(0)
  })

  test("main CTA elements exist and at least one is meaningful", async ({ page }) => {
    await page.goto("/#/")

    const ctas = page.locator("main a:visible, main button:visible")
    const count = await ctas.count()

    expect(count).toBeGreaterThan(0)

    let foundMeaningfulCta = false

    for (let i = 0; i < count; i++) {
      const text = (await ctas.nth(i).innerText()).trim()
      if (text.length > 0) {
        foundMeaningfulCta = true
        break
      }
    }

    expect(foundMeaningfulCta).toBeTruthy()
  })

  test("images are not broken", async ({ page }) => {
    await page.goto("/#/")
    await page.waitForLoadState("networkidle")
    await page.waitForTimeout(1200)

    const images = page.locator("img")
    const count = await images.count()

    expect(count).toBeGreaterThan(0)

    for (let i = 0; i < count; i++) {
      const img = images.nth(i)

      await expect(img).toBeVisible()

      await expect
        .poll(async () => {
          return await img.evaluate((el) => el.complete && el.naturalWidth > 0)
        })
        .toBeTruthy()
    }
  })

  test("navigation links point to valid destinations", async ({ page }) => {
    await page.goto("/#/")

    const navLinks = page.locator("header nav a")
    const count = await navLinks.count()

    expect(count).toBeGreaterThan(0)

    const links = []

    for (let i = 0; i < count; i++) {
      const link = navLinks.nth(i)
      const href = await link.getAttribute("href")
      const text = (await link.innerText()).trim()

      if (!href || isExternalHref(href)) continue

      links.push({ href, text })
    }

    for (const linkData of links) {
      await page.goto("/#/")

      const link = page.locator("header nav a", { hasText: linkData.text }).first()
      await expect(link).toBeVisible()

      await link.click()
      await page.waitForTimeout(300)

      await expect(page.locator("main")).toBeVisible()

      if (isHashSectionHref(linkData.href)) {
        const sectionId = extractSectionId(linkData.href)
        expect(sectionId).toBeTruthy()
        await expect(page.locator(`#${sectionId}`)).toBeVisible()
      }

       if (isHashRouteHref(linkData.href)) {
        await expect
          .poll(() => page.url())
          .toContain(linkData.href)
      }
    }
  })

  test("gallery route works if gallery exists in navigation", async ({ page }) => {
    await page.goto("/#/")

    const galleryLinks = page.locator('header nav a[href*="gallery"]')
    const count = await galleryLinks.count()

    if (count > 0) {
      await galleryLinks.first().click()
      await page.waitForTimeout(300)

      await expect(page).toHaveURL(/#\/gallery/)
      await expect(page.locator("main")).toBeVisible()
      await expect(page.locator("h1")).toBeVisible()
      await expect(page.locator("img").first()).toBeVisible()
    }
  })

  test("page does not contain placeholder content", async ({ page }) => {
    await page.goto("/#/")

    await expect(page.locator("body")).not.toContainText("Lorem ipsum")
    await expect(page.locator("body")).not.toContainText("placeholder")
    await expect(page.locator("body")).not.toContainText("dummy text")
    await expect(page.locator("body")).not.toContainText("Content will be generated by tasks")
  })
})
