export default function Home() {
  return (
    <>
      <section id="hero">
        <h1>Homepage</h1>
        <p>Content will be generated by tasks</p>
      </section>
      <section id="about">
        <h2>About</h2>
      </section>
      <section id="contact">
        <h2>Contact</h2>
      </section>
    </>
  )
}
